name = "RootTaskREPL"
uuid = "5552e04e-9da0-49b1-baf3-128ed75d8338"
authors = ["Mark Kittisopikul <markkitt@gmail.com>"]
version = "0.1.0"

[deps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1"
